pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-1'
    ACCOUNT_ID = '875478187294'   // replace
    ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/myapp"
    IMAGE_NAME = 'myapp'
  }

  stages {

    stage('Checkout Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('docker-image-optimization/demo-nodejs-app') {
        sh 'docker build -t ${IMAGE_NAME}:latest .'
      }
    }
    }

    stage('Login to ECR') {
      steps {
        sh '''
          aws ecr get-login-password --region ${AWS_REGION} | \
          docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
        '''
      }
    }

    stage('Push Image') {
      steps {
        sh '''
          docker tag ${IMAGE_NAME}:latest ${ECR_REPO}:latest
          docker push ${ECR_REPO}:latest
        '''
      }
    }
    stage('Deploy Container') {
  steps {
    sh '''
      docker stop myapp || true
      docker rm myapp || true

      docker pull ${ECR_REPO}:latest

      docker run -d \
        --name myapp \
        -p 3000:3000 \
        ${ECR_REPO}:latest
    '''
  }
}

  }
}
