pipeline {
agent any
environment {
IMAGE_NAME = "myapp"
CONTAINER_NAME = "myapp_container"
PORT = "3000"
}
stages {
stage('Checkout Code') {
steps {
checkout scm
}
}
stage('Build Docker Image') {
steps {
sh """
docker build -t ${IMAGE_NAME}:latest .
"""
}
}
stage('Deploy App on macOS') {
steps {
sh """
docker stop ${CONTAINER_NAME} || true
docker rm ${CONTAINER_NAME} || true
docker run -d \
--name ${CONTAINER_NAME} \
-p ${PORT}:${PORT} \
${IMAGE_NAME}:latest
"""
}
}
}
post {
success {
echo "App deployed successfully 🎉"
}
}
}